### ISSUE TITLE
Update documentation for get-data endpoint

### ISSUE THREAD

**Issue by squalomail** [DataLinx/SqualoMail-PHP-SDK#1]
The documentation for get-data has to be updated as is now possible to get, for each recipients, the information about custom fields, which are showed in response as "user_defined_fields".
At the same time also the SDK itself has to be updated

**Comment by SlimDeluxe** [comment]
I have updated documentation and tests for three requests:
* Create recipient
* Get recipient
* Update recipient

However, the "Update recipient" endpoint returns an empty array for the custom attributes, even though the attribute update is accepted. If you fix this, I can add test for this too. Apart from that, custom attributes are now usable with the API.

**Comment by squalomail** [comment]
I've tested the Update recipient endpoint with custom attributes and it works as it should. 
Request: 
{
	"apiKey":"0vMPFtuzpafJavM5NM0YbPIj9Epfnmog",
    "id":34215,
	"accept": true,
    "autogenerateName": true,
    "confirmed": true,
    "email": "alessio@squalomail.com",
    "enabled": true,
    "html": true,
    "listIds": [114],
    "name": "Alessio",
    "surname": null,
    "gdprCanSend": true,
    "gdprCanTrack": true,
    "customAttributes": [
            {
                "name": "satisfaction",
                "value": "lot"
            }
        ]
}

Can you check again?

**Comment by SlimDeluxe** [comment]
Sure, will check and update shortly.

**Comment by SlimDeluxe** [comment]
@squalomail , it's true, it works, so I implemented the test and updated the readme file. Thanks :)
